#!/usr/bin/env node

require('shelljs/global');

var inquirer = require('inquirer');

var questions = require('./lib/install_questions');
var commands = require('./lib/commands');
var reporter = require('./lib/reporter');

var home = require('./lib/home');

var options = {
    USER_HOME: '/tmp/' + home(),
    WORKSPACE: '/tmp/' + home() + '/workspace',
    GIT_CONFIG_FILE: "dotfiles/gitconfig",
    SRC_DIR: __dirname + '/..',
    TMP_DIR: '/tmp/tools_tmp',
    DOTFILES: ".vimrc .vim .viminfo .bashrc .gitconfig .gitignore_global .inputrc".split(' ')
};

process.on('uncaughtException', function (err) {
    reporter.error(err, true);
    process.exit(1);
});

inquirer.prompt(questions, function(answers) {

    commands.install(options, answers);

    process.exit(0);

});
