#!/bin/bash

chmod +x bash/scripts -R

############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=/home/workspace/config/dotfiles                    # dotfiles directory
olddir=/home/workspace/config/dotfiles/bkp             # old dotfiles backup directory
list=dotfiles_list    # list of files/folders to symlink in homedir

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
echo "Moving any existing dotfiles from ~ to $olddir"
for file in $(cat $list); do
    if [ -f  ~/.$file ]; then
    	mv ~/.$file $olddir
    fi
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done
echo "Creating symlink to vimrc in home directory."
ln -s $dir/vimrc ~/.vim
ln -s $dir/vimrc/vimrc ~/.vimrc

