
alias _='sudo' 
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias ws='cd /home/workspace'
alias myip='curl ifconfig.me'


alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up two directories
alias -- -='cd -'        # Go back

# Shell History
alias h='history'

# Tree
if [ ! -x "$(which tree 2>/dev/null)" ]
then
  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

