pruebas_nombre:
    pattern:  /hola/{name}/
    defaults: { _controller: PruebasPrimerBundle:Default:index, name: "default name from routing.yml" }
    requirements:
        _method: GET
        name: "[\w\.-]+"

pruebas_home:
    pattern:  /
    defaults: { _controller: PruebasPrimerBundle:Default:index }
    requirements:
        _method: GET

pruebas_about:
    pattern:  /about/
    defaults: { _controller: PruebasPrimerBundle:Default:about }
    requirements:
        _method: GET

pruebas_request:
    pattern:  /request/{optional}/
    defaults: { _controller: PruebasPrimerBundle:Default:request, optional: "" }

pruebas_session:
    pattern:  /session
    defaults: { _controller: PruebasPrimerBundle:Default:session }
