pruebas_nombre:
    pattern:  /hola/{name}
    defaults: { _controller: PruebasPrimerBundle:Default:name }
    requirements:
        _method: GET

pruebas_home:
    pattern:  /
    defaults: { _controller: PruebasPrimerBundle:Default:index }
    requirements:
        _method: GET

pruebas_about:
    pattern:  /about
    defaults: { _controller: PruebasPrimerBundle:Default:about }
    requirements:
        _method: GET
