#!/usr/bin/env php
<?php

require_once(__DIR__.'/vendor/autoload.php');

use Symfony\Component\Console as Console;
use Guumaster\Command\HelloWorldCommand;

$app = new Console\Application('Demo App', '0.1');
$app->add(new HelloWorldCommand('hello-world'));

$app->run();
